# Generated by Django 5.1.2 on 2024-10-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='discord_username',
        ),
        migrations.AddField(
            model_name='player',
            name='airlinesim_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
