# Generated by Django 5.1.2 on 2024-10-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_name_player_discord_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
