# Generated by Django 5.1.2 on 2024-10-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_airline_date_formed_airline_parent_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='parent_company',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiaries',
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary1_date_formed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary1_hub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary2_date_formed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary2_hub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary3_date_formed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary3_hub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary4_date_formed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary4_hub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary5_date_formed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary5_hub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='subsidiary5_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
