# Generated by Django 5.1.2 on 2024-10-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_remove_airline_parent_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary1_date_formed',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary1_hub',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary1_name',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary2_date_formed',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary2_hub',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary2_name',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary3_date_formed',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary3_hub',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary3_name',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary4_date_formed',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary4_hub',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary4_name',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary5_date_formed',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary5_hub',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='subsidiary5_name',
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hub', models.CharField(max_length=100)),
                ('date_formed', models.DateField(blank=True, null=True)),
                ('parent_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidiaries', to='players.airline')),
            ],
        ),
    ]
